<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php

/**
 * Template for displaying new products widget
 *
 * @var $block \Magento\Catalog\Block\Product\Widget\NewWidget
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$productCollection = $objectManager->create('Magento\Catalog\Model\ResourceModel\Product\CollectionFactory');
$_productCollection = $productCollection->create()->addAttributeToSelect('*');
$_productCollection->addCategoriesFilter(['in' => 82]);

$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
 

$storeId=$storeManager->getStore()->getStoreId();

$baseurl=$objectManager->get('Magento\Store\Model\StoreManagerInterface')
            ->getStore($storeId)
            ->getBaseUrl();

$helper = $objectManager->get('Magento\Wishlist\Helper\Data');


?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php
    $viewMode = 'grid';
    $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
?>
<div class="block widget block-products-list hotdeals-slider-block <?php /* @escapeNotVerified */ echo "grid"; ?> comman-hot-deal">
        <div class="block-content">
            <div class="products-<?php /* @escapeNotVerified */ echo 'grid'; ?> <?php /* @escapeNotVerified */ echo 'grid'; ?>">
                <ol id="blowout-slider" class="product-items hotdeals-slider-ul">
                    <?php $iterator = 1; ?>
<?php
foreach($_productCollection as $_product)
        {

            $productArr=$_product->getData();
            $produrl=$_product->getProductUrl();
                            if(strpos($produrl,"?SID"))
                            {
                                $produrlArr=explode("?",$produrl);
                                $produrl=$produrlArr[0];
                            }
             echo($iterator++ == 1) ? '<li class="product-item hotdeals-item hotdeals-slider-li">' : '</li><li class="product-item hotdeals-item hotdeals-slider-li">';
	    ?>
               <div class="product-item-info1 hotdeals-slider-li-inner">

                    <a href="<?php echo $produrl?>">
			<?php //print_r($productArr);exit;?>
			<?php if(isset($productArr['small_image']) && $productArr['small_image']!=''):?>
                        <img src="<?php echo $baseurl."pub/media/catalog/product".$productArr['small_image']?>" />
			<?php else:?>
                        <img src="<?php echo $baseurl."pub/placeholder/small_image.jpg"?>" />
			<?php endif?>
                    </a>
                    
                                        
                    <div class="product-item-details">
                        
                        <strong class="product name product-item-name">
                            <a href="<?php echo $produrl?>">
                                <?php /* @escapeNotVerified */ echo $productArr['name']; ?>
                                </a>
                            
                        </strong>
                        
                        <div class="product-item-inner-details">
<?php

$reviewFactory = $objectManager->create('Magento\Review\Model\Review');


$reviewFactory->getEntitySummary($_product, $storeId);

$_ratingSummary = $_product->getRatingSummary()->getRatingSummary();
//var_dump($ratingSummary);

        //$_ratingSummary = $block->getRatingSummary($product);
        $_reviewCount = $_product->getRatingSummary()->getReviewsCount();

 if($_ratingSummary){ ?>
    <div class="product-reviews-summary short">
        <div class="rating-summary">
            <div title="<?php echo (int)$_ratingSummary; ?>%" class="rating-result">
                <span style="width:<?php echo (int)$_ratingSummary; ?>%"><span><?php echo (int)$_ratingSummary; ?>%</span></span>
            </div>
        </div>
<!--        <div class="reviews-actions">
            <?php echo __('('.$_reviewCount.')'); ?>
        </div>-->
    </div>
    <?php } ?>
                  
                            <?php 
    $priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');?>
<?php echo $formattedPrice = $priceHelper->currency($productArr['price'], true, false);?>

                        </div>
                    </div>
                    
                    
             </div>	    <?php
?>
                        <?php echo($iterator == $_productCollection->count()+1) ? '</li>' : '' ?>
<?php
                     
        }
            
            ?>
            
    </ol>
</div>
</div>
</div>
<script type="text/javascript" charset="utf-8">
    require([
        'jquery',
        'owl_carousel',

    ], function ($) {
        'use strict';

        $(document).ready(function(){
            $('#blowout-slider').owlCarousel({nav:true,dots:false,items:4});


        });

    });
</script>

<?php endif;?>
